pollers:
  - name: "localPoller"
    frequencyMs: 5000
    backend:
      type: local
      path: "/data/input"
    actions:
        "/data/input/location1": ["MoveFileAction", "/home/gpfarina/test/file1.txt", "/home/gpfarina/test/file1old.txt"]
        "/data/input/location2": ["HttpRequest", "GET", "www.google.com"]
  - name: "awsPoller"
    frequencyMs: 7000
    actions:
      "/data/inputS3": ["LogEvent"]
    backend:
      type: s3
      prefix: "s3"
      bucket: "bucket"
      path: "/data/inputS3"