pollers:
  - name: "localPoller"
    frequencyMs: 5000
    backend:
      type: LOCAL
    actions:
        "/home/gian-pietro/pollaris/data/test1": LOGEVENT
  - name: "localPoller2"
    frequencyMs: 5000
    backend:
      type: LOCAL
    actions:
        "/home/gian-pietro/pollaris/data/test2": LOGEVENT