pollers:
  - name: "localPoller"
    frequencyMs: 5000
    backend:
      type: LOCAL
    actions:
        "/data/input/location1": LOGEVENT
        "/data/input/location2": "LOGEVENT"
  - name: "awsPoller"
    frequencyMs: 7000
    backend:
      type: AWS
      prefix: "s3"
      bucket: "bucket"
    actions:
      "/data/locationS3": "LogEvent"